blank_issues_enabled: true
contact_links:
  - name: Do you want to discuss EIP ideas or ask questions about the process?
    url: https://ethereum-magicians.org/
    about: Use the Fellowship of Ethereum Magicians for EIP-related discussion!
