on:
  schedule:
    # A job that runs every sunday at 00:00
    - cron:  '0 0 * * 0'

name: Auto Stagnant Bot
jobs:
  auto_merge_bot:
    if: github.repository == 'ethereum/eips'
    runs-on: ubuntu-latest
    name: Auto Stagnant Bot
    steps:
      - name: Checkout
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - name: Setup Node.js Environment
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: '14'
      - name: auto-stagnant-bot
        uses: ethereum/EIP-Bot@b3ac0ba3600aea27157fc68d1e36c08cc5a6db77 # mark-eips-stale
        id: auto-stagnant-bot
        with:
          GITHUB-TOKEN: ${{ secrets.TOKEN }}
